plugin.id=tuoke-module-iot-plugin-emqx
plugin.class=cn.metast.tuoke.module.iot.plugin.emqx.config.IotEmqxPlugin
plugin.version=1.0.0
plugin.provider=tuoke
plugin.dependencies=
plugin.description=tuoke-module-iot-plugin-emqx-1.0.0
