plugin.id=tuoke-module-iot-plugin-http
plugin.class=cn.metast.tuoke.module.iot.plugin.http.config.IotHttpVertxPlugin
plugin.version=1.0.0
plugin.provider=tuoke
plugin.dependencies=
plugin.description=tuoke-module-iot-plugin-http-1.0.0